sift/concerts/urls.py
from django.conf.urls import url

from . import views

app_name = 'concerts'
urlpatterns = [
    url(r'^$', views.UpcomingShows.as_view(), name='upcoming_shows'),
    url(r'^artists/$', views.ArtistsIndex.as_view(), name='artists'),
    url(r'^venues/$', views.VenuesIndex.as_view(), name='venues'),
    url(r'^all/$', views.ConcertsIndex.as_view(), name='all_concerts'),
]

sift/sift/urls.py
# -*- coding: utf-8 -*-
# sift/urls.py

"""sift URL Configuration"""

from django.conf.urls import url, include
#from django.contrib import admin

from concerts.views import Home

urlpatterns = [
    url(r'^concerts/', include('concerts.urls')),
    url(r'^$', Home.as_view(), name='sift_home'),
    #url(r'^admin/', admin.site.urls),
]

sift/concerts/models.py
from django.db import models

class Artist(models.Model):
    name = models.CharField(max_length=200, unique=True)
    re_string = models.CharField(max_length=200)
    spotify_id = models.CharField(max_length=200, blank=True)
    is_active = models.BooleanField(default=True)

    # vs. custom manager?
    @classmethod
    def add_artist(cls, artist_name):
        """
        Get Spotify ID and regex string for complete database entry.

        Assumes artist DNE; calling code should check for artist in DB first.
        """

        from concerts.utils import get_spotify_id, make_artist_regex

        spotify_id = get_spotify_id(artist_name)
        re_string = make_artist_regex(artist_name)
        artist = Artist.objects.create(
            name=artist_name,
            re_string=re_string,
            spotify_id=spotify_id
        )
        return artist

    def __str__(self):
        return "({}) {} - Spotify ID: {}".format(self.pk,
                                                 self.name,
                                                 self.spotify_id)

class Venue(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=300)
    schedule_url = models.CharField(max_length=300)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class Concert(models.Model):
    billing = models.CharField(max_length=400)
    artists = models.ManyToManyField(Artist)
    venue = models.ForeignKey(
        Venue,
        on_delete = models.SET_NULL,
        blank = True,
        null = True,
    )
    date_time = models.DateTimeField()
    price = models.CharField(max_length=100)
    url = models.CharField(max_length=300)
    date_scraped = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "{0} - {1} at {2}".format(
            self.date_time.strftime('%m.%d'),
            self.billing,
            self.venue,
        )

class ConcertMatch(models.Model):
    artists = models.ManyToManyField(Artist)
    concert = models.OneToOneField(
        Concert,
        on_delete = models.CASCADE,
    )

sift/concerts/views.py
# -*- coding: utf-8 -*-
# concerts/views.py

from datetime import datetime

from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic

from .models import Artist, Concert, ConcertMatch, Venue

class Home(generic.View):
    """
    Return cover page.
    """

    def get(self, request):

        from random import choice

        taglines = (
            "Shake it 'til you bake it",
            "Whatever will bewilder me",
            "Properly following proper protocols",
            "Stopped to watch my emotions sway",
            "Reckon luck sees us the same",
            "The ocean floor is hidden from your viewing lens",
        )
        context = {'tagline': choice(taglines)}
        return render(request, 'concerts/sift_home.html', context)

class UpcomingShows(generic.View):
    """
    View list of concerts that have a tracked artist in their billing.
    """

    def get(self, request):
        """
        Return Concerts that have matched an artist in their billing,
        ordered by date ascending.
        """

        matched_concert_ids = list(ConcertMatch.objects.values_list('concert', flat=True))
        matches = Concert.objects.filter(id__in=matched_concert_ids).order_by('date_time')
        if Concert.objects.count():
            last_updated = Concert.objects.latest('date_scraped').date_scraped
        # TODO handle empty DB
        else:
            last_updated = datetime(1900,1,1)
        context = {
            'matches': matches,
            'last_updated': last_updated,
        }

        return render(request, 'concerts/upcoming_concerts.html', context)

class ArtistsIndex(generic.ListView):
    """
    View all artists being tracked.
    """
    queryset = Artist.objects.filter(is_active=True).order_by('name')

class VenuesIndex(generic.ListView):
    """
    View all venues being tracked.
    """
    queryset = Venue.objects.filter(is_active=True).order_by('name')

class ConcertsIndex(generic.View):
    """
    View all concerts in the DB, regardless of artist matches.
    """

    def get(self, request):
        """
        Return a list of all Concerts in the database.
        """
        concerts = Concert.objects.order_by('date_time')
        if concerts:
            last_updated = concerts[0].date_scraped
        # TODO handle empty DB
        else:
            last_updated = datetime(1900,1,1)
        context = {
            'concert_list': concerts,
            'last_updated': last_updated,
        }
        return render(request, 'concerts/concert_list.html', context)

if __name__=='__main__':
    pass

sift/concerts/templates/concerts/artist_list.html
{% extends "concerts/base.html" %}

{% block content %}
    <h2>Artists tracked</h2>
    <ul>
        {% for artist in artist_list %}
            <li>{{ artist.name }}</li>
        {% endfor %}
    </ul>
{% endblock %}

sift/concerts/templates/concerts/base.html
<!DOCTYPE html>

{% load tz %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="siftshows">
        <meta name="author" content="JR">
        <!-- <link rel="icon" href="../../favicon.ico"> -->

        <title>siftshows</title>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

        <!-- barf -->
        <style>
        #spotify-link {
            color: #009900;
        }

        a:hover {
            text-decoration: underline;
        }

        body {
            padding-top: 40px;
            padding-bottom: 0px;
        }
        </style>

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug
        <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
        -->

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

{% include "concerts/navbar.html" %}

    <body>

        <div class="container">

            {% timezone "America/Chicago" %}
            {% block content %}
            {% endblock content %}
            {% endtimezone %}

        </div>


        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <!-- hmm
        <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
        <script src="../../dist/js/bootstrap.min.js"></script>
        - - IE10 viewport hack for Surface/desktop Windows 8 bug - -
        <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
        -->

    </body>
</html>

sift/concerts/templates/concerts/concert_list.html
{% extends "concerts/base.html" %}

{% block content %}
    <h2>All concerts</h2>
    <i>last updated {{ last_updated|date:"SHORT_DATE_FORMAT" }}</i>
    {% for concert in concert_list %}
        <h3><a href={{ concert.url }}>{{ concert.billing }}</a></h3>
        <p>{{ concert.venue.name }} - {{ concert.date_time }}, {{ concert.price }}</p>
    {% endfor %}
{% endblock %}

sift/concerts/templates/concerts/concertmatch_list.html
{% extends "concerts/base.html" %}

{% load tz %}

{% block content %}
    <h2>Upcoming concerts</h2>
    <ul>
        {% for concert in matches %}
            <li><h3>{{ concert.billing }} at {{ concert.venue }}</h3>
                <p>{{ concert.date_time|timezone:"America/Chicago" }}, {{ concert.price }}</p>
                <p>Matches artists
                {% for artist in concert.artists.all %}
                    '{{ artist.name }}', {% endfor %}
                </p>
                <p><a href={{ concert.url }}>Link</a></p>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

sift/concerts/templates/concerts/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
        <!--
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      -->
      <a class="navbar-brand" href="{% url 'sift_home' %}">sift</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'concerts:upcoming_shows' %}">Upcoming Concerts</a></li>
        <li><a href="{% url 'concerts:artists' %}">Artists</a></li>
        <li><a href="{% url 'concerts:venues' %}">Venues</a></li>
        <li><a href="{% url 'concerts:all_concerts' %}">All Shows</a></li>
      </ul>
    </div>
  </div>
</nav>

<!-- original /////
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Project name</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
      </ul>
    </div>
  </div>
</nav>
-->

sift/concerts/templates/concerts/sift_home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="siftstuff">
    <meta name="author" content="">

    <title>sift</title>

    <!-- Optional theme-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.0/examples/cover/cover.css" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <div class="masthead clearfix">
            <div class="inner">
              <!-- <h3 class="masthead-brand">sift</h3> -->
                <nav class="nav masthead-nav">
                    <a class="nav-link" href="{% url 'concerts:upcoming_shows' %}">Concerts</a>
                </nav>
            </div>
          </div>
          <div class="inner cover">
            <h1 class="cover-heading">sift</h1>
            <p class="lead">{{ tagline }}</p>
            <!--
            <p class="lead">
              <a href="#" class="btn btn-lg btn-default">Learn more</a>
            </p>
            -->
          </div>
          <div class="mastfoot">
            <div class="inner">
              <p>
                J. Ravesloot, 2017.  <a href="https://github.com/industryjhr/sift_app">Github</a>
              </p>
              <p style='font-size:10px;'>Cover template design by <a href="https://twitter.com/mdo">@mdo</a> for Bootstrap.</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

    <!-- from bootstrap site
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    - - IE10 viewport hack for Surface/desktop Windows 8 bug - -
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
    -->
  </body>
</html>

sift/concerts/templates/concerts/upcoming_concerts.html
{% extends "concerts/base.html" %}
{% block content %}

    <h2>Upcoming concerts</h2><i>last updated {{ last_updated|date:"SHORT_DATE_FORMAT" }}</i>
    <ul>
        {% for concert in matches %}
            <li>
                <h3>{{ concert.billing }}</h3><h4> at {{ concert.venue }}</h4>
                <p>{{ concert.date_time }} | Tickets {{ concert.price }} | <a href={{ concert.url }}>Show page</a></p>
                <p>Matches artists
                {% for artist in concert.artists.all %}
                    {% if artist.spotify_id %}
                        '{{ artist.name }}' <a id="spotify-link" href=https://play.spotify.com/artist/{{ artist.spotify_id }}>(Spotify)</a>, 
                    {% else %}
                        '{{ artist.name }}', 
                    {% endif %}
              {% endfor %}
                </p>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

sift/concerts/templates/concerts/venue_list.html
{% extends "concerts/base.html" %}

{% block content %}
    <h2>Venues tracked</h2>
    {% for venue in venue_list %}
        <h3><a href={{ venue.schedule_url }}>{{ venue.name }}</a></h3>
        <p>{{ venue.address }}</p>
    {% endfor %}
{% endblock %}

sift/concerts/templates/shows/artist_list.html
{% extends "shows/base.html" %}

{% block content %}
    <h2>Artists tracked</h2>
    <ul>
        {% for artist in artist_list %}
            <li>{{ artist.name }}</li>
        {% endfor %}
    </ul>
{% endblock %}

sift/concerts/templates/shows/concertmatch_list.html
{% extends "shows/base.html" %}

{% block content %}
    <h2>Upcoming concerts</h2>
    <ul>
        {% for concert in matches %}
            <li><h3>{{ concert.billing }} at {{ concert.venue }}</h3>
                <p>{{ concert.date_time|date:"DATETIME_FORMAT" }}, {{ concert.price }}</p>
                <p><a href={{ concert.url}}>Link</a></p>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

sift/concerts/templates/shows/venue_list.html
{% extends "shows/base.html" %}

{% block content %}
    <h2>Venues tracked</h2>
    {% for venue in venue_list %}
        <h3>#{{ venue.pk }} <a href={{ venue.schedule_url }}>{{ venue.name }}</a></h3>
        <p>{{ venue.address }}</p>
    {% endfor %}
{% endblock %}